---
galaxy_info:
  author: Karl Hepworth
  description: Installs hub, software from Jetbrains
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
  - name: Debian
    versions:
    - all
  - name: EL
    versions:
    - 6
    - 7
  galaxy_tags:
  - jetbrains
  - team
  - hub
  categories:
  - development
  - system
  - web
  dependencies:
  - fubarhouse.commons