- assert:
    that: lightdm_state in ('present',)
- assert:
    that: ansible_os_family == 'Debian'
- assert:
    that: ansible_service_mgr == 'systemd'

- name: install lightdm
  apt:
    name:
      - lightdm
      - libglib2.0-bin
    state: latest
  notify: restart lightdm

- name: write lightdm configuration
  template:
    src: lightdm.conf.j2
    dest: '{{ lightdm_conf_directory }}/{{ lightdm_override_filename }}'
    owner: "{{ root_user|default('root') }}"
    group: "{{ root_group|default('root') }}"
    mode: 0644
  register: lightdm_config

- name: apply glib schemas changes
  command: '/usr/bin/glib-compile-schemas {{ lightdm_glib_schemas_directory }}'
  when: lightdm_config.changed
  notify: restart lightdm

- name: install xserver-xorg-video-dummy
  apt:
    name:
      - xserver-xorg-video-dummy
    state: latest
  when: lightdm_xorg_create_video_dummy
  notify: restart lightdm

- name: write xorg dummy configuration
  template:
    src: xorg.conf.j2
    dest: '{{ lightdm_xorg_conf_directory }}/{{ lightdm_xorg_override_filename }}'
    owner: "{{ root_user|default('root') }}"
    group: "{{ root_group|default('root') }}"
    mode: 0644
  when: lightdm_xorg_create_video_dummy
  notify: restart lightdm

- name: delete xorg dummy configuration
  file:
    path: '{{ lightdm_xorg_conf_directory }}/{{ lightdm_xorg_override_filename }}'
    state: absent
  when: not lightdm_xorg_create_video_dummy
