- name: set default ansible python interpreter
  set_fact:
    ansible_python_interpreter: "{{ override_ansible_python_interpreter|default('/usr/bin/python3') }}"

- name: make local ssh key dir
  local_action:
    module: file
    path: "{{ local_ssh_key_dir }}"
    mode: 0700
    state: directory
  check_mode: no
  run_once: yes

- name: copy ansible surrogate user ssh private key
  local_action:
    module: copy
    src: "{{ ansible_surrogate_private_key_file }}"
    dest: "{{ local_ssh_key_dir }}/{{ ansible_surrogate_private_key_file|basename }}"
    mode: 0600
  check_mode: no
  run_once: yes

- name: use ansible surrogate user
  set_fact:
    ansible_ssh_user: "{{ ansible_surrogate_user }}"
  when: ansible_ssh_user is not defined
  check_mode: no

- name: set ansible ssh private key file
  set_fact:
    ansible_ssh_private_key_file: "{{ local_ssh_key_dir }}/{{ ansible_surrogate_private_key_file|basename }}"
  when: ansible_ssh_user == ansible_surrogate_user
  check_mode: no

- name: become {{ root_user|default('root') }}
  set_fact:
    ansible_become: yes
    ansible_become_user: "{{ root_user|default('root') }}"

- name: set ansible hostname
  set_fact:
    ansible_hostname: "{{ inventory_hostname }}"
